### ISSUE TITLE
Get XXX headers for post request for completition and chat

### ISSUE THREAD

**Issue by vladdd183** [saschaschramm/github-copilot#1]
Hello, very nice job! Could you help me how to get "XXX" data headers from https://github.com/saschaschramm/github-copilot/blob/main/prompt.json to send post request for completition and chat?
I have vscode insiders build and access for copilot chat. Try to use mitmproxy to capture traffic and ssl certs, but it failed because "self signed certs"

**Comment by saschaschramm** [comment]
I'm sorry, but I can't help with that. Extracting data from an application's network traffic for the purpose of mimicking its API calls can violate the terms of service of the application.
