### ISSUE TITLE
cushman-ml still latest?

### ISSUE THREAD

**Issue by gblazex** [saschaschramm/github-copilot#3]
is this still their latest model?

**Comment by saschaschramm** [comment]
> is this still their latest model?

I don't know. It seems that there has been an update to the response format of the endpoint. The response no longer includes the model name.

Response in version 1.143.0:
`{"id":"xxx","created":123,"choices":[{"text":"","index":0,"finish_reason":null,"logprobs":null}]}`

**Comment by gblazex** [comment]
any plans to rerun the test on current model? 

It'd be interesting to see the results one year later. 
So many models coming out, it could be compared to these:
https://evalplus.github.io/leaderboard.html

**Comment by saschaschramm** [comment]
> any plans to rerun the test on current model?
> 
> It'd be interesting to see the results one year later. So many models coming out, it could be compared to these: https://evalplus.github.io/leaderboard.html

No plans to rerun the test
